import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../Components/Header";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    
    
    <html lang="en">
      <body className={inter.className}>
        
        <div className="bg-blue-950">
        
      


      

        
          <Header/>
          <Navbar/>
  
        
        {children}
        <Footer/>

      
        </div>
        </body>
    </html>
  
  );
}
